name: Build and Release APK

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: 'latest'

    - name: Install dependencies
      run: flutter pub get
      working-directory: ./android

    - name: Run Flutter doctor
      run: flutter doctor -v

    - name: Build APK
      run: flutter build apk --release
      working-directory: ./android

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-apk
        path: ./android/build/app/outputs/flutter-apk/app-*.apk
